language: node_js

node_js:
  - 'node'

install:
  - npm i

script:
  - cd template
  - npm i
  - npm run dev
  - npm run build

cache:
  directories:
    - 'node_modules'
    - 'template/node_modules'
