language: node_js

node_js:
  - 'node'

install:
  - npm i

script:
  - yes "" | vue init . test
  - cd test
  - npm run lint
  - npm test
  - npm run build

cache:
  directories:
    - 'node_modules'